import packages for JUnit 5
To avoid errors of this shape when running tests from Eclipse:

org.junit.platform.commons.JUnitException: TestEngine with ID
'junit-jupiter' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
...
Caused by: java.lang.SecurityException: class
"org.junit.jupiter.api.extension.ExtensionContext"'s signer information
does not match signer information of other classes in the same package