disabled edelta-maven-plugin
And use xtext-maven-plugin properly configured.

The edelta-maven-plugin gives too many problems, maybe due to new
dependencies in Xtext (Guice 7, no more javax.inject, etc.) leading to
several failures in unit tests and also when running it.

For example,
[ERROR] testDebugLogging(edelta.maven.plugin.EdeltaMojoTest)  Time
elapsed: 0.774 s  <<< ERROR!
java.lang.ExceptionInInitializerError
Caused by: java.lang.IllegalArgumentException:
org.eclipse.sisu.Parameters is not a binding annotation. Please annotate
it with @BindingAnnotation.

[ERROR] testProjectWithSkip(edelta.maven.plugin.EdeltaMojoTest)  Time
elapsed: 0.002 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class
org.eclipse.sisu.wire.ParameterKeys
Caused by: java.lang.ExceptionInInitializerError: Exception
java.lang.IllegalArgumentException: org.eclipse.sisu.Parameters is not a
binding annotation. Please annotate it with @BindingAnnotation. [in
thread "main"]