removed mockito from edelta-maven-plugin
Because of (maybe due to interference between Maven deps and p2 deps):

Error:  testProjectWithErrorFailOnValidationErrorFalse(edelta.maven.plugin.EdeltaMojoTest)
Time elapsed: 0.091 s  <<< ERROR!
java.lang.IllegalStateException: Could not initialize plugin: interface
org.mockito.plugins.MockMaker (alternate: null)
	at edelta.maven.plugin.EdeltaMojoTest.spyLog(EdeltaMojoTest.java:189)
	at edelta.maven.plugin.EdeltaMojoTest.testProjectWithErrorFailOnValidationErrorFalse(EdeltaMojoTest.java:146)
Caused by: java.lang.IllegalStateException: Internal problem occurred,
please report it. Mockito is unable to load the default implementation
of class that is a part of Mockito distribution. Failed to load
interface org.mockito.plugins.MockMaker
	at edelta.maven.plugin.EdeltaMojoTest.spyLog(EdeltaMojoTest.java:189)
	at edelta.maven.plugin.EdeltaMojoTest.testDebugLogging(EdeltaMojoTest.java:162)
Caused by: java.lang.reflect.InvocationTargetException
	at edelta.maven.plugin.EdeltaMojoTest.spyLog(EdeltaMojoTest.java:189)
	at edelta.maven.plugin.EdeltaMojoTest.testDebugLogging(EdeltaMojoTest.java:162)
Caused by: java.lang.ExceptionInInitializerError
	at edelta.maven.plugin.EdeltaMojoTest.spyLog(EdeltaMojoTest.java:189)
	at edelta.maven.plugin.EdeltaMojoTest.testDebugLogging(EdeltaMojoTest.java:162)
Caused by: java.lang.SecurityException: class
"javax.annotation.Nonnull"'s signer information does not match signer
information of other classes in the same package
	at edelta.maven.plugin.EdeltaMojoTest.spyLog(EdeltaMojoTest.java:189)
	at edelta.maven.plugin.EdeltaMojoTest.testDebugLogging(EdeltaMojoTest.java:162)